export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const REGISTER_SUCESS = 'RESIGESTER_SUCESSS';
export const REGISTER_FAIL = 'REGIESTER_FAIL';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
